[workspace]

members = [
    "anagrambot",
    "anabot"
]

[profile.release]
# enable 'fat' (cross-crate) link time optimization
lto = true

# a release build with debug info
# useful for profiling (for example, with heaptrack)
[profile.release-with-debug]
inherits = "release"
debug = true