[workspace]

members = [
    "anagrambot",
    "anagrambot_cli"
]

# a release build with debug info
# useful for profiling (for example, with heaptrack)
[profile.release-with-debug]
inherits = "release"
debug = true